### ISSUE TITLE
Setup version3 branch to accept pull requests and run CI/CD, without publishing.

### ISSUE THREAD

**Issue by jwdonahue** [maythamfahmi/CryptoNet#100]
Setup version3 branch to accept pull requests and run CI/CD, without publishing.

I merged vesion3 with my local working branch, to avoid creating a lot of conflicts, but when I setup a draft PR, it would only allow me to target merging to main, which is not what I want to be testing for at the moment.

It's easy enough to configure on github, but you may need to implement some branch awareness in your build scripts, to avoid publishing bits from the version3 branch automagically.

From #90 

Improve releasing version so that build number become patch number in version or something like that

In most environments, there's many more builds and consequent build numbers, than their are versioned releases. I like to use a scheme where there's two flavors of build. One for testing pull requests and one for building and publishing a new package.

**Comment by maythamfahmi** [comment]
Now we have 5 pipelines

1. for Continuous Integration
2. fro Continuous Deployment, which deploy artifact with version 3.0.0-pre-yymmdd.1.1 on github action.
3. code coverage
4. Continuous Deployment, triggered when release is tagget with version, i will push nuget on nuget.org
5. publish documentation

![image](https://github.com/user-attachments/assets/289dc5d4-5b0a-49d1-b33b-00a69c933b81)
