### ISSUE TITLE
[Bug]: CryptoNetAes.ExportKey takes bool? set to null, and never uses it.

### ISSUE THREAD

**Issue by jwdonahue** [maythamfahmi/CryptoNet#101]
### What happened?

Naming vs function aside, why default a bool to null, and never use it?

### Version

2.4.x >= (Default)

### Relevant log output

```shell
public string ExportKey(bool? privateKey = null)
    {
        return CryptoNetUtils.ExportAndSaveAesKey(Aes);
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maythamfahmi** [comment]
one way of sloving this is by introducing to interfaces one fo RSA and one for AES, some thing like


```
public interface ICryptoNetAes : ICryptoNet
{
    string ExportKey();
    void ExportKeyAndSave(FileInfo fileInfo);
}
```

and

```
public interface ICryptoNetRsa : ICryptoNet
{
    string ExportKey(bool privateKey = false);
    void ExportKeyAndSave(FileInfo fileInfo, bool privateKey = false);
}
```

I am going this way, is there otehr options?

**Comment by jwdonahue** [comment]
Something like this maybe?

```
public record Key : IGetKey, ISaveKey
{
    string Getkey();
    void SaveKey(string filename);
    void SaveKey(FileInfo fileInfo);
}
```

```
public interface ICryptoNetAes : ICryptoNet
{
    Key GetKey();
}

```
public interface ICryptoNetRsa : ICryptoNet
{
    Key GetPrivateKey()
    Key GetPublicKey()
}
```

**Comment by maythamfahmi** [comment]
Have a nice evening  and sleep well

**Comment by jwdonahue** [comment]
Maybe a hierarchy of Key types, derived from Key, with a handful of static factory methods for each of the specialized types?

**Comment by maythamfahmi** [comment]
#101 will also sovle #102.

**Comment by maythamfahmi** [comment]
PR https://github.com/maythamfahmi/CryptoNet/pull/106
