### ISSUE TITLE
[feature request]: Inline documentation with description

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#104]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

It would be good a some pont when version 3 at its end, an inline documenation to be add to constructors and method. 

### Priority Level

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jwdonahue** [comment]
What kind of "inline" documentation? 

XML comments:

```
/// <Summary>
/// Constructor...
/// </Summary>
```
Or something else?

**Comment by maythamfahmi** [comment]
exactly XML comments.

**Comment by maythamfahmi** [comment]
Good input. My primary thought was about the documentation information that pops up when using IntelliSense.

**Comment by jwdonahue** [comment]
I'd have to verify, but I think IntelliSense picks up the summary and the listed exceptions, if the XmlDoc tags are there, but defaults to some number of whatever comments are associated with the method. At least that's the recollection I have from decades past.

But ya, I agree, developer supports are very important.

**Comment by maythamfahmi** [comment]
old documentation is ported to docfx https://maythamfahmi.github.io/CryptoNet, but under API new version3 is found. When we are about the endpoint version 3 relase, we will update the examples in seperate feature branch related to #123
