### ISSUE TITLE
Hard Coded Store

### ISSUE THREAD

**Issue by 66656c6c6f7574** [maythamfahmi/CryptoNet#16]
CryptoNetUtils.GetCertificateFromStore has the store location hard coded, the ability to specify the store location and name would be good.

**Comment by maythamfahmi** [comment]
@66656c6c6f7574  thank you for the I am working on a newer version and will take this with me.

**Comment by maythamfahmi** [comment]
@66656c6c6f7574 this feature now is implemented in breaking change release 2.1.0, try it and let me know, other wise you are welcome to create a new feature request. :)
