### ISSUE TITLE
Version 3: Help wanted

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#71]
**Hej Future Contributors ❤️,**

📢 I am working on version 3 of this package and would love your help! If you're interested in contributing, please reply to this thread and I will get in touch. Here’s what I need assistance with:

1. Ideas for Version 3 and future features
2. Writing Tests to achieve at least 90% code coverage
3. Implementing New Features
4. Code Reviews
5. Code Improvements
6. Documentation Enhancement
7. Pipeline Improvements
8. Bug Fixing
9. Performance Testing and Optimization

✅ If you can and would like to contribute to any of these areas 👆, please let me know in this thread. 

🙏 Thanks!

**Comment by masterpeter2720** [comment]
I would still continue working on this with you @maythamfahmi

**Comment by jwdonahue** [comment]
I may be able to contribute something. What have you got in mind?

**Comment by maythamfahmi** [comment]
@jwdonahue thansk, I spending some time currently to make a list of features. is there any sepcific area you like to work with from the above list og just any thing withing the list? General speaking, The core functionality will be the same, it is more new features, split the code in core encryption/decryption functionality and helper functionality, of course if you have any ideas, you are welcome. Let me know your thoughts.

**Comment by jwdonahue** [comment]
Some ideas come to mind:
- Add secure key storage and retrieval.
- The test app should be more clearly named.

**Comment by maythamfahmi** [comment]
@jwdonahue  both ideas are excellent, I will add them to the list, and you will be welcome to pick them for further development, of course if there are other areas you like to for example documentation review, you are welcome to do that. I hope with few days I am finish a list of things, we can go a head with next version.

**Comment by maythamfahmi** [comment]
I have included you as contributor @jwdonahue

**Comment by maythamfahmi** [comment]
I have created version3 branch, you are welcome to start branching out and make 2 feature request for the 2 changes you suggest. Make PR to version3 and assign me as reviewer 😃

**Comment by maythamfahmi** [comment]
We are already started version 3, if some one want to contribute, just comment here with reference @maythamfahmi
