### ISSUE TITLE
[feature request]: The test app should be more clearly named

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#84]
### Is your feature request related to a problem? Please describe.

The test app should be more clearly named

### Describe the solution you'd like

The test app should be more clearly named

### Priority Level

Medium

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by maythamfahmi** [comment]
@jwdonahue I was thinking remove application test to unit test and give then make clearly named. What do you think?

**Comment by maythamfahmi** [comment]
I fully agree, this is what now is made on #87

**Comment by jwdonahue** [comment]
I think all of that functionality could be moved into separate unit tests and the entire project deleted.

**Comment by jwdonahue** [comment]
See #97 [feature request]: Add an Examples folder to the project hierarchy.

**Comment by jwdonahue** [comment]
The current CryptoNet.Cli project contains a mix of good example code and a program that reads like a list of unit tests. We should fix that.

Are you okay with me dropping some examples into an Example folder and adding unit tests for each of them?

**Comment by maythamfahmi** [comment]
@jwdonahue  go a head it is all fine with me,

**Comment by jwdonahue** [comment]
Okay.

I should have that built by EOD (UTC-8), tomorrow morning at the latest.

**Comment by jwdonahue** [comment]
This is still a WIP.

Draft PR: https://github.com/maythamfahmi/CryptoNet/pull/103/files

I have not removed CryptoNet.Cli yet. I still need to evaluate the coverage situation.

**Comment by maythamfahmi** [comment]
I like the new folder structure.
