### ISSUE TITLE
[feature request]: Test coverage need to reach higher rate than today 70%

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#86]
### Is your feature request related to a problem? Please describe.

not directly

### Describe the solution you'd like

We want to imporve test coverage. Today it is aroud 70%, every thing 80% and up would be cool to reach.

Our ulitmate goal is to reach 100%.

### Priority Level

Low

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by maythamfahmi** [comment]
with all new tests introduces we are already at above 80%, I think for this stage it is fine.

![image](https://github.com/user-attachments/assets/308a73f3-af64-4e3a-ba62-da4747c4c34a)

**Comment by jwdonahue** [comment]
I am generally not happy with anything less than 100%, except for the few occasional code paths that are more costly to cover, than expert review. Those are rare, and usually involve impossible corner-cases/code paths that are their purely to make the compiler happy (ie; default cases in switch statements, or exceptional paths that should never be hit). Simple libraries should approach 100% coverage, but not at the expense of alternate path permutations through the code. Complete coverage != thorough testing.

I am pleased to see the improvement in coverage though.

**Comment by maythamfahmi** [comment]
I agree with you if we can do 100% that would be awesome.
