### ISSUE TITLE
[feature request]: CLI examples should converted to Unit test

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#87]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

CLI examples should converted to function test

### Priority Level

Medium

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jwdonahue** [comment]
I merged @maythamfahmi 's changes, fixed all the merge conflicts, and It think #103 is ready for review.

**Comment by maythamfahmi** [comment]
Part of #84
