### ISSUE TITLE
[feature request]: Separate unit tests from integration tests

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#88]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

Unit test need to be splitter in unit test and integration test

### Priority Level

Medium

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jwdonahue** [comment]
I usually drive my integration/acceptance testing, through unit tests of my examples. I don't usually do much more than that for simple libraries. I think of integration testing as more of a domain for more complex systems.

**Comment by maythamfahmi** [comment]
I got the point, If have migrated cli test to unit test, now we have only unit testing #87

**Comment by maythamfahmi** [comment]
no integration tests, but functional test Part of #84
