### ISSUE TITLE
[feature request]: Improve releasing version so that build number become patch number in version or something like that

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#90]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

Improve releasing version so that build number become patch number in version or something like that

### Describe alternatives you've considered

Improve releasing version so that build number become patch number in version or something like that

### Priority Level

Medium

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jwdonahue** [comment]
In most environments, there's many more builds and consequent build numbers, than their are versioned releases. I like to use a scheme where there's two flavors of build. One for testing pull requests and one for building and publishing a new package.

**Comment by maythamfahmi** [comment]
this will be part of #100
