### ISSUE TITLE
[feature request]: Implement DES algorithm

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#94]
Inspiration
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.des.create?view=net-6.0

**Comment by jwdonahue** [comment]
Do you really want to promote use of an algorithm that is known to be insecure?

https://search.brave.com/search?q=Is+DES+considered+secure%3F&summary=1&summary_og=9b36ac7a622cacab00d548

**Comment by maythamfahmi** [comment]
@jwdonahue it sound like a valid point, it was asked few years back. But think based on this knowledge, this should not be done. I will close this feature.
