### ISSUE TITLE
[feature request]: Add an Examples folder to the project hierarchy.

### ISSUE THREAD

**Issue by jwdonahue** [maythamfahmi/CryptoNet#97]
### Contact Details

joseph@sharperhacksllc.cm

### Is your feature request related to a problem? Please describe.

V2 examples are embedded in the README.md file. I have found that good working examples, make excellent components for integration/acceptance testing, driven by unit tests.

### Describe the solution you'd like

- Create Examples directory.
- Add to that, an example for each algorithm/major feature of CryptoNet, as separate console projects.
- Add unit test to the CryptoNet.UnitTests to cover each new example app.
- TBD: List of example worthy features.

### Priority Level

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jwdonahue** [comment]
I have driven some development this way. Create a feature example project and unit test driver, for TDD and then I wind up with a descent example usage that I can point to in my docs (whenever I get around to those).

**Comment by jwdonahue** [comment]
Draft PR: https://github.com/maythamfahmi/CryptoNet/pull/103/files

I have not removed CryptoNet.Cli yet. I still need to evaluate the coverage situation.

**Comment by maythamfahmi** [comment]
Thanks, I am reviewing now, just have seen some files like CryptoNet.vtg, CryptoNet.vpwhist, CryptoNet.vpw, CryptoNet.vpj is those suppose to be part of the solution? maybe we need to add following to gitignore

# Ignore SlickEdit files.
*.vpj
*.vpw
*.vpwhist
*.vtg

Let me know what you think?

**Comment by maythamfahmi** [comment]
With this solved, #87 and #88 will be not needed and can be close when this is merged to https://github.com/maythamfahmi/CryptoNet/tree/version3

**Comment by jwdonahue** [comment]
Yes! I forgot to add that to the .gitignore file, will fix shortly...

**Comment by jwdonahue** [comment]
All comments resolved.
